<?php
defined('MOODLE_INTERNAL') || die();

/**
 * Adds a new instance of the gemini module.
 *
 * @param stdClass $gemini The object containing the data to insert.
 * @param mod_gemini_mod_form $mform The form object (optional).
 * @return int The id of the new instance.
 */
function gemini_add_instance($gemini, $mform = null) {
    global $DB;

    $gemini->timecreated = time();
    $gemini->timemodified = time();

    // Insert the main instance record.
    $id = $DB->insert_record('gemini', $gemini);

    // If we had content generation logic in the main form, we would handle it here,
    // but we are using a "Wizard" approach AFTER creation, so we just save the shell.
    
    return $id;
}

/**
 * Updates an instance of the gemini module.
 *
 * @param stdClass $gemini The object containing the data to update.
 * @param mod_gemini_mod_form $mform The form object (optional).
 * @return bool True on success.
 */
function gemini_update_instance($gemini, $mform = null) {
    global $DB;

    $gemini->timemodified = time();
    $gemini->id = $gemini->instance;

    return $DB->update_record('gemini', $gemini);
}

/**
 * Deletes an instance of the gemini module.
 *
 * @param int $id The id of the instance to delete.
 * @return bool True on success.
 */
function gemini_delete_instance($id) {
    global $DB;

    if (!$gemini = $DB->get_record('gemini', array('id' => $id))) {
        return false;
    }

    // Delete associated content first.
    $DB->delete_records('gemini_content', array('geminiid' => $gemini->id));

    // Delete the instance.
    $DB->delete_records('gemini', array('id' => $gemini->id));

    return true;
}

/**
 * Supports standard Moodle features.
 *
 * @param string $feature The feature to check support for.
 * @return mixed
 */
function gemini_supports($feature) {
    switch($feature) {
        case FEATURE_MOD_INTRO: return true;
        case FEATURE_SHOW_DESCRIPTION: return true;
        case FEATURE_BACKUP_MOODLE2: return true;
        case FEATURE_COMPLETION_TRACKS_VIEWS: return true;
        case FEATURE_COMPLETION_HAS_RULES: return true;
        case FEATURE_GRADE_HAS_GRADE: return true;
        case FEATURE_GROUPS: return true;
        default: return null;
    }
}

/**
 * Obtains the automatic completion state for this gemini activity on any 'view' based criteria.
 *
 * @param object $course Course
 * @param object $cm Course-module
 * @param int $userid User ID
 * @param bool $type Type of comparison (or/and; can be used as return value if no conditions are met)
 * @return bool True if completed, false if not, $type if conditions not set.
 */
function gemini_get_completion_state($course, $cm, $userid, $type) {
    global $DB;

    $gemini = $DB->get_record('gemini', array('id' => $cm->instance));

    if (!$gemini) {
        return $type;
    }

    // Check custom completion rules (e.g., 'viewed all flashcards')
    // For now we will rely on standard 'view' completion, but this hook is here for future expansion.
    
    return $type;
}

/**
 * Serves the audio files generated by the plugin.
 *
 * @param stdClass $course The course object
 * @param stdClass $cm The course module object
 * @param context $context The context object
 * @param string $filearea The name of the file area
 * @param array $args Extra arguments (itemid, path, filename)
 * @param bool $forcedownload Whether to force download
 * @param array $options Additional options
 * @return bool False if file not found, otherwise sends file
 */
function gemini_pluginfile($course, $cm, $context, $filearea, $args, $forcedownload, array $options=array()) {
    global $DB;

    if ($context->contextlevel != CONTEXT_MODULE) {
        return false;
    }

    require_login($course, true, $cm);

    if (!in_array($filearea, ['audio', 'quiz'])) {
        return false;
    }

    $itemid = (int)array_shift($args);

    $fs = get_file_storage();
    $relativepath = implode('/', $args);
    $fullpath = "/$context->id/mod_gemini/$filearea/$itemid/$relativepath";

    if (!$file = $fs->get_file_by_hash(sha1($fullpath)) or $file->is_directory()) {
        return false;
    }

    send_stored_file($file, 0, 0, true, $options); // Force download = false
}

/**
 * Update grades in the gradebook.
 *
 * @param object $gemini
 * @param int $userid
 * @param object $nullifnone
 */
function gemini_update_grades($gemini, $userid = 0, $nullifnone = true) {
    global $CFG;
    require_once($CFG->libdir.'/gradelib.php');

    if ($userid) {
        if ($nullifnone) {
            $grade = new stdClass();
            $grade->userid = $userid;
            $grade->rawgrade = 100;
        } else {
            $grade = $nullifnone;
        }
        gemini_grade_item_update($gemini, $grade);
    }
}

/**
 * Create/update grade item for this activity.
 *
 * @param object $gemini
 * @param object|array $grades
 * @return int 0 if ok, error code otherwise
 */
function gemini_grade_item_update($gemini, $grades = null) {
    global $CFG;
    require_once($CFG->libdir.'/gradelib.php');

    $params = array('itemname' => $gemini->name);
    $params['gradetype'] = GRADE_TYPE_VALUE;
    $params['grademax'] = 100;
    $params['grademin'] = 0;

    if ($grades === 'reset') {
        $params['reset'] = true;
        $grades = null;
    }

    return grade_update('mod/gemini', $gemini->course, 'mod', 'gemini', $gemini->id, 0, $grades, $params);
}

